export const banner = `// Autogenerated. Do not edit.
import * as mobx from './mobx.mjs'
import * as mst from './mobx-state-tree.mjs'
import * as pluginsCore from './@hoc/plugins-core.mjs'
import { hocComponents } from './@hoc/components.mjs'
import * as hocModels from './@hoc/models.mjs'
`

export const footer = `
if (miniApp) {
  const { registerPlugin, extendPlugin } = pluginsCore
  if (typeof miniApp === 'object' && Array.isArray(miniApp)) {
    for (let idx = 0; idx < miniApp.length; idx++ ) {
      miniApp[idx] = miniApp[idx].isBase ? extendPlugin(miniApp[idx]) : miniApp[idx]
      registerPlugin(miniApp[idx])
    }
  } else {
    miniApp = miniApp.isBase ? extendPlugin(miniApp) : miniApp
    registerPlugin(miniApp)
  }
  window.miniApp = miniApp
}
`

export const iifeArgs = {
  'mobx': 'mobx',
  'mobx-state-tree': 'mst',
  '@hoc/plugins-core': 'pluginsCore',
  '@hoc/components': 'hocComponents',
  '@hoc/models': 'hocModels',
}
