import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import json from '@rollup/plugin-json'

const externals = [
  'mobx',
  'mobx-state-tree',
  'styled-components',
  '@hoc/plugins-core',
  '@hoc/components',
]

const banner = `// Autogenerated. Do not edit.
import * as mobx from './mobx.mjs'
import * as mst from './mobx-state-tree.mjs'
import * as styledComponents from './styled-components.mjs'
import * as pluginsCore from './@hoc/plugins-core.mjs'
import * as hocComponents from './@hoc/components.mjs'
import * as hocModels from './@hoc/models.mjs'
`
const footer = `
if (miniApp) {
  const { registerPlugin, extendPlugin } = pluginsCore
  miniApp = miniApp.isBase ? extendPlugin(miniApp) : miniApp
  registerPlugin(miniApp)
  window.miniApp = miniApp
}
`

export default {
  input: 'index.js',
  output: {
    file: './.bundle.mini.js',
    format: 'iife',
    name: 'miniApp',
    banner: banner,
    footer: footer,
    exports: 'auto',
    globals: {
      '@hoc/plugins-core': 'pluginsCore',
      'mobx-state-tree': 'mst',
      'mobx': 'mobx',
      'styled-components': 'styledComponents',
      '@hoc/components': 'hocComponents',
      '@hoc/models': 'hocModels',
    },
  },    
  external: externals,
  plugins: [
    json(),
    resolve({
      mainFields: ['module', 'jsnext', 'main'],
    }),
    commonjs(),
  ],
}
